const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Timeline,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Flowchart,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.PlatformInfo,
		C3.Plugins.EMI_INDO_node_axios,
		C3.Plugins.AdvancedRandom,
		C3.Plugins.Internationalization,
		C3.Plugins.AJAX,
		C3.Plugins.Dictionary,
		C3.Plugins.Json,
		C3.Plugins.Arr,
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Behaviors.Physics,
		C3.Behaviors.Tween,
		C3.Behaviors.Rex_MoveTo,
		C3.Plugins.Spritefont2,
		C3.Plugins.NinePatch,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Flash,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Physics.Acts.Teleport,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.PickAll,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.TiledBg.Acts.MoveForward,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.MoveForward,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Exps.UID,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Spritefont2.Exps.X,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.TiledBg.Cnds.PickChildren,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Exps.ImageWidth,
		C3.Plugins.TiledBg.Acts.LoadURL,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Spritefont2.Exps.Tags,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.TiledBg.Exps.BBoxLeft,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.TiledBg.Exps.BBoxRight,
		C3.Plugins.TiledBg.Exps.BBoxTop,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.TiledBg.Exps.BBoxBottom,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.ScriptsInEvents.Gameplayereventsheet_Event80_Act1,
		C3.ScriptsInEvents.Gameplayereventsheet_Event81_Act1,
		C3.ScriptsInEvents.Gameplayereventsheet_Event82_Act1,
		C3.ScriptsInEvents.Gameplayereventsheet_Event83_Act1,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Exps.ZIndex,
		C3.ScriptsInEvents.Gameplayereventsheet_Event86_Act2,
		C3.ScriptsInEvents.Gameplayereventsheet_Event87_Act18,
		C3.ScriptsInEvents.Gameplayereventsheet_Event91_Act2,
		C3.ScriptsInEvents.Gameplayereventsheet_Event92_Act18,
		C3.ScriptsInEvents.Gameplayereventsheet_Event96_Act2,
		C3.ScriptsInEvents.Gameplayereventsheet_Event97_Act18,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.ScriptsInEvents.Gameplayereventsheet_Event105_Act2,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.Sprite.Acts.AddChild
	];
};
self.C3_JsPropNameTable = [
	{FloatingTimelineController: 0},
	{Mouse: 0},
	{Touch: 0},
	{FlowchartController: 0},
	{Audio: 0},
	{本地存储: 0},
	{设备信息: 0},
	{axios: 0},
	{高级随机: 0},
	{本地化: 0},
	{AJAX: 0},
	{字典: 0},
	{JSON: 0},
	{Array: 0},
	{level: 0},
	{maxLevel: 0},
	{name: 0},
	{health: 0},
	{maxHealth: 0},
	{attack: 0},
	{attackSpeed: 0},
	{defense: 0},
	{dodgeRate: 0},
	{attackTime: 0},
	{hurt: 0},
	{Attacking: 0},
	{Attacking10: 0},
	{Attacking11: 0},
	{Attacking12: 0},
	{Attacking13: 0},
	{Attacking14: 0},
	{Attacking15: 0},
	{Attacking16: 0},
	{Attacking17: 0},
	{Attacking18: 0},
	{Attacking19: 0},
	{Attacking2: 0},
	{Attacking20: 0},
	{Attacking3: 0},
	{Attacking4: 0},
	{Attacking5: 0},
	{Attacking6: 0},
	{Attacking7: 0},
	{Attacking8: 0},
	{Attacking9: 0},
	{Player: 0},
	{type: 0},
	{Eq1: 0},
	{Eq2: 0},
	{Eq3: 0},
	{EqCheck: 0},
	{EqTab: 0},
	{EqTarget1: 0},
	{EqTarget2: 0},
	{EqTarget3: 0},
	{Chest: 0},
	{Trash: 0},
	{Giant: 0},
	{GreenMonster: 0},
	{GreenMonster2: 0},
	{GreenMonster3: 0},
	{Monster: 0},
	{Monster10: 0},
	{Monster11: 0},
	{Monster12: 0},
	{Monster13: 0},
	{Monster2: 0},
	{Monster3: 0},
	{Monster4: 0},
	{Monster5: 0},
	{Monster6: 0},
	{Monster7: 0},
	{Monster8: 0},
	{Monster9: 0},
	{StoneMonster: 0},
	{StoneMonster2: 0},
	{StoneMonster3: 0},
	{SuperGiant: 0},
	{Mummy: 0},
	{Mummy2: 0},
	{Mummy3: 0},
	{Group3: 0},
	{Group5: 0},
	{Group8: 0},
	{Group2: 0},
	{Group9: 0},
	{HealthInline: 0},
	{HealthOutline: 0},
	{LevelInline: 0},
	{LevelOutline: 0},
	{StartGame: 0},
	{物理: 0},
	{Ground: 0},
	{PlayerStand: 0},
	{PlayerStart: 0},
	{PointerPixel: 0},
	{Tween: 0},
	{MoveTo: 0},
	{Coin: 0},
	{Boom: 0},
	{Floating: 0},
	{MonsterStart: 0},
	{Content: 0},
	{TestPointer: 0},
	{"9patch": 0},
	{Background1: 0},
	{Background2: 0},
	{Background3: 0},
	{BottomBackground: 0},
	{GameMask: 0},
	{TiledBackground2: 0},
	{TiledBackground3: 0},
	{DragDrop: 0},
	{Equipment: 0},
	{Character: 0},
	{闪烁: 0},
	{补间动画: 0},
	{Players: 0},
	{Monsters: 0},
	{EquipmentCard: 0},
	{GameObject: 0},
	{GameStatus: 0},
	{EqTabNumber: 0},
	{MonsterNumber: 0},
	{CurrentLevel: 0},
	{count: 0},
	{createX: 0},
	{createY: 0},
	{monsterUid: 0},
	{damage: 0},
	{isFight: 0},
	{DraggingUID: 0},
	{EqTargetX: 0},
	{EqTargetY: 0},
	{EqStartX: 0},
	{EqStartY: 0},
	{ChestNumber: 0},
	{ShouldSkip: 0},
	{uid: 0}
];

self.InstanceType = {
	FloatingTimelineController: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	FlowchartController: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	本地存储: class extends self.IInstance {},
	设备信息: class extends self.IInstance {},
	axios: class extends self.C3.Plugins.EMI_INDO_node_axios.Instance {},
	高级随机: class extends self.IInstance {},
	本地化: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	字典: class extends self.IDictionaryInstance {},
	JSON: class extends self.IJSONInstance {},
	Array: class extends self.IArrayInstance {},
	Attacking: class extends self.ISpriteInstance {},
	Attacking10: class extends self.ISpriteInstance {},
	Attacking11: class extends self.ISpriteInstance {},
	Attacking12: class extends self.ISpriteInstance {},
	Attacking13: class extends self.ISpriteInstance {},
	Attacking14: class extends self.ISpriteInstance {},
	Attacking15: class extends self.ISpriteInstance {},
	Attacking16: class extends self.ISpriteInstance {},
	Attacking17: class extends self.ISpriteInstance {},
	Attacking18: class extends self.ISpriteInstance {},
	Attacking19: class extends self.ISpriteInstance {},
	Attacking2: class extends self.ISpriteInstance {},
	Attacking20: class extends self.ISpriteInstance {},
	Attacking3: class extends self.ISpriteInstance {},
	Attacking4: class extends self.ISpriteInstance {},
	Attacking5: class extends self.ISpriteInstance {},
	Attacking6: class extends self.ISpriteInstance {},
	Attacking7: class extends self.ISpriteInstance {},
	Attacking8: class extends self.ISpriteInstance {},
	Attacking9: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	Eq1: class extends self.ISpriteInstance {},
	Eq2: class extends self.ISpriteInstance {},
	Eq3: class extends self.ISpriteInstance {},
	EqCheck: class extends self.ISpriteInstance {},
	EqTab: class extends self.ISpriteInstance {},
	EqTarget1: class extends self.ISpriteInstance {},
	EqTarget2: class extends self.ISpriteInstance {},
	EqTarget3: class extends self.ISpriteInstance {},
	Chest: class extends self.ISpriteInstance {},
	Trash: class extends self.ISpriteInstance {},
	Giant: class extends self.ISpriteInstance {},
	GreenMonster: class extends self.ISpriteInstance {},
	GreenMonster2: class extends self.ISpriteInstance {},
	GreenMonster3: class extends self.ISpriteInstance {},
	Monster: class extends self.ISpriteInstance {},
	Monster10: class extends self.ISpriteInstance {},
	Monster11: class extends self.ISpriteInstance {},
	Monster12: class extends self.ISpriteInstance {},
	Monster13: class extends self.ISpriteInstance {},
	Monster2: class extends self.ISpriteInstance {},
	Monster3: class extends self.ISpriteInstance {},
	Monster4: class extends self.ISpriteInstance {},
	Monster5: class extends self.ISpriteInstance {},
	Monster6: class extends self.ISpriteInstance {},
	Monster7: class extends self.ISpriteInstance {},
	Monster8: class extends self.ISpriteInstance {},
	Monster9: class extends self.ISpriteInstance {},
	StoneMonster: class extends self.ISpriteInstance {},
	StoneMonster2: class extends self.ISpriteInstance {},
	StoneMonster3: class extends self.ISpriteInstance {},
	SuperGiant: class extends self.ISpriteInstance {},
	Mummy: class extends self.ISpriteInstance {},
	Mummy2: class extends self.ISpriteInstance {},
	Mummy3: class extends self.ISpriteInstance {},
	Group3: class extends self.ISpriteInstance {},
	Group5: class extends self.ISpriteInstance {},
	Group8: class extends self.ISpriteInstance {},
	Group2: class extends self.ISpriteInstance {},
	Group9: class extends self.ISpriteInstance {},
	HealthInline: class extends self.ITiledBackgroundInstance {},
	HealthOutline: class extends self.ITiledBackgroundInstance {},
	LevelInline: class extends self.ITiledBackgroundInstance {},
	LevelOutline: class extends self.ITiledBackgroundInstance {},
	StartGame: class extends self.ISpriteInstance {},
	Ground: class extends self.ISpriteInstance {},
	PlayerStand: class extends self.ISpriteInstance {},
	PlayerStart: class extends self.ISpriteInstance {},
	PointerPixel: class extends self.ISpriteInstance {},
	Coin: class extends self.ISpriteInstance {},
	Boom: class extends self.ISpriteInstance {},
	Floating: class extends self.ISpriteFontInstance {},
	MonsterStart: class extends self.ISpriteInstance {},
	Content: class extends self.ISpriteFontInstance {},
	TestPointer: class extends self.ISpriteInstance {},
	_9patch: class extends self.IWorldInstance {},
	Background1: class extends self.ITiledBackgroundInstance {},
	Background2: class extends self.ITiledBackgroundInstance {},
	Background3: class extends self.ITiledBackgroundInstance {},
	BottomBackground: class extends self.ITiledBackgroundInstance {},
	GameMask: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	Equipment: class extends self.ISpriteInstance {},
	Character: class extends self.ISpriteInstance {},
	Players: class extends self.ISpriteInstance {},
	Monsters: class extends self.ISpriteInstance {},
	EquipmentCard: class extends self.ISpriteInstance {},
	GameObject: class extends self.ISpriteInstance {}
}